### ISSUE TITLE
Graph editor with source

### ISSUE THREAD

**Issue by Sairony** [Demigiant/demilib#7]
Is it possible to get the graph editor with source instead of built as DLL? It seems grabbing just _Demigiant.Libraries\Core isn't enough. Also, it would be nice with some super simple example just to get the graph editor drawing on a window. I took a guess that creating a DG.DemiEditor.DeGUINodeSystem.NodeProcess on top of a editor window would be enough, but that doesn't seem to fly ( although I get no errors, I also don't get any results ).

**Comment by Demigiant** [comment]
Hi,

I'm not sure what you mean with "graph editor". If you mean the framework to make node-based windows, there's an example [in this project](DemiLib.UnityTests.Unity5) (see the "_Examples/DeGUI" DeGUISample scene, and the DeSample gameObject to launch a DeGUINodeSampler—sorry if it's complicated to reach/read, but I built it for internal testing for now).
There's a lot of stuff written in the method's XML comments though, so intellisense should tell you a lot when you try to access a NodeProcess.

And sorry but I prefer much more to code these things in assemblies, because they're more manageable and more powerful :P
